### PR TITLE
leubot overhaul – Controller and Router refactoring with proper request handlers with CORS and superuser

### LINKED ISSUE #11: CORS headers on all paths
It should be sufficient to add the proper w.Header().Set("...", "...") with leubot's resources in robot.go and user.go

In Java, this would be something like:

corsHeaders.put(com.google.common.net.HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN, Arrays.asList("*"));
corsHeaders.put(com.google.common.net.HttpHeaders.ACCESS_CONTROL_ALLOW_CREDENTIALS, Arrays.asList("true"));
corsHeaders.put(com.google.common.net.HttpHeaders.ACCESS_CONTROL_ALLOW_METHODS, Arrays.asList(HttpMethod.GET.name(), HttpMethod.POST.name(), HttpMethod.PUT.name(), HttpMethod.DELETE.name(), HttpMethod.HEAD.name(), HttpMethod.OPTIONS.name()));

(with the proper METHODS of course, where OPTIONS and HEAD should be present in all)

### LINKED ISSUE #13: Migrate from Gopkg to go-mod
Installing a specific version with GOPATH is bothersome.

### LINKED ISSUE #14: Externalize the leubot path name
The endpoint name (e.g., leubot[1|2]), as well as the version (e.g., 1.2.2), needs to be automatically set when `leubot` is run.
- use an option for the name
- use the tag for the version

This will be resolved after the AI4Industry summer school.

### LINKED ISSUE #17: Create a super user when accessed with the secret token
This should guarantee the consistency of /user resource state.

### PR DESCRIPTION
**Pull request by iomz**
Fixes the bug mentioned in #11 – updating the PR #12

### CODE REVIEW

**Comment by iomz** [comment]
Fixed https://github.com/Interactions-HSG/leubot/issues/11#issuecomment-887324312
@smnmyr please check again

**Comment by iomz** [comment]
@smnmyr can you check it now with leubot1? Now it should be free from unexpected freezing and you don't have to create a user – if the master token is used then a superuser is automatically created.
Also added /sleep if you can find it useful somehow.

**Comment by smnmyr** [comment]
Thank you, Iori!

**Review by smnmyr — COMMENTED** [review]
Thank you!

**Review by smnmyr — APPROVED** [review]

**Pull request merged**
